import sender

recruitment_body = """<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Hi</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">,</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I&rsquo;m reaching out to</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> because I run a Facebook Group with 120,000+ current high achieving Australian students. </span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Having run this group for the last four years, I&rsquo;ve noticed a pattern in the enormous amount of student discussion and questions about how to effectively make the transition to full time employment, and at the moment - these questions are answered by other students who share various articles and resources.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We&rsquo;ve already partnered with companies like RMIT, Bank of Melbourne and Latrobe University in assisting students make the transition to employment - and we thought that you could be interested in stepping up and becoming the trusted advisor for students in applying for, and receiving graduate positions. </span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We&rsquo;re currently having a chat with all the main graduate employers in Australia to see who could provide the most assistance to these students, and we&rsquo;d love to have a chat with you.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Please feel free to schedule a time that you&rsquo;d be free to chat at this link: </span><a style="text-decoration: none;" href="https://calendly.com/charlie-f"><span style="font-size: 9.5pt; font-family: Arial; color: #1155cc; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">https://calendly.com/charlie-f</span></a><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, or reply by email.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Look forward to chatting soon,</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Charlie</span></p>"""
recruitment_subject = "120,000+ students wanting guidance on joining {}"
clothing_body = """<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Hi</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">,</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I&rsquo;m reaching out as I run Facebook Groups with 100,000+ current students and having run this group for the last four years, I&rsquo;ve noticed an enormous amount of student discussion and interest in </span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">{}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">At the moment - these discussion is simply amongst the students who share various articles and resources - however we see an opportunity for a clothing brand to jump in and interact directly with these students directly.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We're already worked alongside large corporates like PWC, Bank of Melbourne and RMIT and thus we're currently having a chat with all the main clothing brands to see who could provide value to these students. We&rsquo;d love to have a chat with you.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Please feel free to schedule a time that you&rsquo;d be free to chat at this link: </span><a style="text-decoration: none;" href="https://calendly.com/charlie-f"><span style="font-size: 9.5pt; font-family: Arial; color: #1155cc; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">https://calendly.com/charlie-f</span></a><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, or reply by email.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Look forward to chatting soon,</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Charlie</span></p>"""
clothing_subject = "100k+ students talking about {}"
student_body = """<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Hi</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">,</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I&rsquo;m reaching out to</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> because I run a Facebook Group with 120,000+ current students.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Having run this group for the last four years, I&rsquo;ve noticed a pattern in the enormous amount of student discussion and questions about overseas travel, and how to best organise a gap year or exchange that is truly memorable. At the moment - these questions are answered by other students who share various articles and resources, however, we see an opportunity for a travel provider, like </span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">{}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> to step in and assist the students in organising the students overseas travel. &nbsp;</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We're already worked alongside large corporates like PWC, Bank of Melbourne and RMIT and we're currently in the process of having a chat with all the main travel providers to see who could assist the 120,000+ students. We&rsquo;d love to have a chat with you.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Please feel free to schedule a time that you&rsquo;d be free to chat at this link: </span><a style="text-decoration: none;" href="https://calendly.com/charlie-f"><span style="font-size: 9.5pt; font-family: Arial; color: #1155cc; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">https://calendly.com/charlie-f</span></a><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, or reply by email.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Look forward to chatting soon,</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Charlie</span></p>"""
student_subject = "120,000+ students wanting guidance on joining travelling overseas"
phone_body = """<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Hi</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">,</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I&rsquo;m reaching out to</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> because I run a Facebook Group with 120,000+ current Australian students.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Having run this group for the last four years, I&rsquo;ve noticed a pattern in the enormous amount of student discussion and confusion about how to choose the best mobile package. At the moment - these questions are answered by other students who share various articles and resources however, we seen an opportunity for </span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">{}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> to come into this group and assist the students in finding the best mobile package.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We're already worked alongside large corporates like PWC, Bank of Melbourne and RMIT and we're currently in the process of having a chat with all the main mobile providers to see who could best assist the 120,000+ students on finding the best phone package. We&rsquo;d love to have a chat with you.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Please feel free to schedule a time that you&rsquo;d be free to chat at this link: </span><a style="text-decoration: none;" href="https://calendly.com/charlie-f"><span style="font-size: 9.5pt; font-family: Arial; color: #1155cc; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">https://calendly.com/charlie-f</span></a><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, or reply by email.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Look forward to chatting soon,</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Charlie</span></p>"""
phone_subject = "120,000+ students wanting guidance on their first phone plan"
edu_body = """<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Hi</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">,</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I&rsquo;m reaching out to</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> because I run a Facebook Group with 120,000+ current year 11 and 12 students.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Having run this group for the last four years, I&rsquo;ve seen an enormous amount of student discussion and questions about how to effectively make the transition to university. At the moment - these questions are answered by other students who share various articles and resources, however, we see an opportunity for an education provider to directly interact with these students. </span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">In Victoria and NSW, we&rsquo;ve already had Latrobe University &amp; University of Wollongong step in and speak directly to these students, and we&rsquo;re currently in the process of selecting one more educational provider to interact with these students. We&rsquo;d love to have a chat. </span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Please feel free to schedule a time that you&rsquo;d be free to chat at this link: </span><a style="text-decoration: none;" href="https://calendly.com/charlie-f"><span style="font-size: 9.5pt; font-family: Arial; color: #1155cc; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">https://calendly.com/charlie-f</span></a><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, or reply by email.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Look forward to chatting soon,</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Charlie</span></p>"""
edu_subject = "120,000+ students wanting guidance on joining {}"
bar_body = """<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Hi</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #222222; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #222222; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">,</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I&rsquo;m reaching out as I run Facebook Groups with 100,000+ current students and having run this group for the last four years, I&rsquo;ve noticed an enormous amount of student discussion and questions about local clubs and bars, particularly</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">At the moment - these questions are answered by other students who share various articles and resources - however we see an opportunity for a club/bar to jump in and talk to these students directly.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We're already worked alongside large corporates like PWC, Bank of Melbourne and RMIT and thus we're currently having a chat with all the main bars/clubs to see who could provide value to these students. We&rsquo;d love to have a chat with you.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Please feel free to schedule a time that you&rsquo;d be free to chat at this link: </span><a style="text-decoration: none;" href="https://calendly.com/charlie-f"><span style="font-size: 9.5pt; font-family: Arial; color: #1155cc; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">https://calendly.com/charlie-f</span></a><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, or reply by email.</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Look forward to chatting soon,</span></p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Charlie</span></p>"""
bar_subject = "100k+ students talking about {}"
balls_body = """<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Hi</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">,</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I&rsquo;m reaching out to</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> because I run a Facebook Group with 120,000+ current students.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Having run this group for the last four years, I&rsquo;ve noticed a pattern in the enormous amount of student discussion and finding the perfect attire for student balls and formals, and the best stores for students. At the moment - these questions are answered by other students who share various articles and resources, however, we see an opportunity for </span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">{}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> to step in and assist the students in finding their perfect formal attire.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We're already worked alongside large corporates like PWC, Bank of Melbourne and RMIT and we're currently in the process of having a chat with all the main clothing providers to see who could assist the 120,000+ students on finding the best attire. We&rsquo;d love to have a chat with you.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Please feel free to schedule a time that you&rsquo;d be free to chat at this link: </span><a style="text-decoration: none;" href="https://calendly.com/charlie-f"><span style="font-size: 9.5pt; font-family: Arial; color: #1155cc; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">https://calendly.com/charlie-f</span></a><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, or reply by email.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Look forward to chatting soon,</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Charlie</span></p>"""
balls_subject = "120,000+ students wanting guidance on buying their formal attire"
sender.send_letters(subject=recruitment_subject, body=recruitment_body, name_index=2, company_index=0, email_index=4,
                    filename="Recruitment.csv")
sender.send_letters(subject=clothing_subject, body=clothing_body, name_index=1, company_index=0, email_index=2,
                    filename="Clothing.csv")
sender.send_letters(subject=student_subject, body=student_body, name_index=1, company_index=0, email_index=3,
                    filename="StudentTravel.csv")
sender.send_letters(subject=phone_subject, body=phone_body, name_index=1, company_index=0, email_index=2,
                    filename="MobilePhoneCompanies.csv")
sender.send_letters(subject=edu_subject, body=edu_body, name_index=2, company_index=0, email_index=4,
                    filename="EduProviders.csv")
sender.send_letters(subject=bar_subject, body=bar_body, name_index=2, company_index=0, email_index=4,
                    filename="Bars.csv")
sender.send_letters(subject=balls_subject, body=balls_body, name_index=1, company_index=0, email_index=2,
                    filename="Balls.csv")
