import html2text
text = """<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Hi</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">,</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">I&rsquo;m reaching out to</span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> {}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> because I run a Facebook Group with 120,000+ current students.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Having run this group for the last four years, I&rsquo;ve noticed a pattern in the enormous amount of student discussion and finding the perfect attire for student balls and formals, and the best stores for students. At the moment - these questions are answered by other students who share various articles and resources, however, we see an opportunity for </span><strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">{}</span></strong><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"> to step in and assist the students in finding their perfect formal attire.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We're already worked alongside large corporates like PWC, Bank of Melbourne and RMIT and we're currently in the process of having a chat with all the main clothing providers to see who could assist the 120,000+ students on finding the best attire. We&rsquo;d love to have a chat with you.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Please feel free to schedule a time that you&rsquo;d be free to chat at this link: </span><a style="text-decoration: none;" href="https://calendly.com/charlie-f"><span style="font-size: 9.5pt; font-family: Arial; color: #1155cc; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: underline; -webkit-text-decoration-skip: none; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">https://calendly.com/charlie-f</span></a><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">, or reply by email.</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Look forward to chatting soon,</span></p>
<p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;">&nbsp;</p>
<p style="line-height: 1.656; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 9.5pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Charlie</span></p>"""
print(html2text.html2text(text))
